// Dev-only codegen script — not imported by src/, not shipped in the app bundle.
// Run via `npm run structures:build`. Regenerates src/data/structures/gfp1EMA.ts from the
// vendored raw PDB file at scripts/structures/1EMA.pdb (downloaded once from RCSB,
// https://files.rcsb.org/download/1EMA.pdb — public domain).
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { parsePDB, PDB_RESNAME_TO_ONE_LETTER, type SecondaryStructureRange } from '../src/biology/pdb'

const __dirname = dirname(fileURLToPath(import.meta.url))

const CHAIN_ID = 'A'

function secondaryStructureAt(
  resSeq: number,
  ranges: SecondaryStructureRange[],
): 'helix' | 'sheet' | 'coil' {
  for (const range of ranges) {
    if (range.chainId !== CHAIN_ID) continue
    if (resSeq >= range.startResSeq && resSeq <= range.endResSeq) return range.type
  }
  return 'coil'
}

function main() {
  const rawPath = resolve(__dirname, 'structures/1EMA.pdb')
  const raw = readFileSync(rawPath, 'utf-8')
  const parsed = parsePDB(raw)

  // Reference protein + resSeq numbers come from resolved CA atoms only (not SEQRES) — this
  // feature can only ever render/highlight a residue it has an XYZ position for. This also
  // means the derived reference protein is legitimately shorter than avGFP's full ~238
  // residues wherever the crystal structure has unresolved loops/termini, or (as is the case
  // for GFP's own chromophore, residues 65-67, which 1EMA records as a single modified
  // HETATM residue "CRO" rather than three separate standard-residue ATOM CA entries) a
  // structurally real gap rather than a parsing bug.
  const chainACA = parsed.atoms
    .filter((a) => a.chainId === CHAIN_ID && a.name === 'CA')
    .sort((a, b) => a.resSeq - b.resSeq)

  const residues = chainACA.map((atom) => {
    const oneLetter = PDB_RESNAME_TO_ONE_LETTER[atom.resName]
    if (!oneLetter) {
      throw new Error(`Unrecognized residue name "${atom.resName}" at resSeq ${atom.resSeq}`)
    }
    return {
      resSeq: atom.resSeq,
      resName: oneLetter,
      ss: secondaryStructureAt(atom.resSeq, parsed.secondaryStructure),
      ca: [atom.x, atom.y, atom.z] as [number, number, number],
    }
  })

  console.log(`Parsed ${parsed.atoms.length} ATOM records, ${parsed.secondaryStructure.length} secondary structure ranges.`)
  console.log(`Chain ${CHAIN_ID} resolved CA residues: ${residues.length}`)
  console.log(`First residues: ${residues.slice(0, 8).map((r) => r.resName).join('')}...`)
  console.log(`Last residues:  ...${residues.slice(-8).map((r) => r.resName).join('')}`)
  console.log(`resSeq range: ${residues[0]?.resSeq} - ${residues[residues.length - 1]?.resSeq}`)

  const body = residues
    .map(
      (r) =>
        `  { resSeq: ${r.resSeq}, resName: '${r.resName}', ss: '${r.ss}', ca: [${r.ca[0]}, ${r.ca[1]}, ${r.ca[2]}] },`,
    )
    .join('\n')

  const output = `// Generated by scripts/buildStructureData.ts from scripts/structures/1EMA.pdb — do not hand-edit.
// Source: RCSB PDB entry 1EMA (Ormö et al. 1996), chain A, Cα atoms only, public domain.
import type { StructureResidue } from './index'

export const GFP_1EMA_RESIDUES: StructureResidue[] = [
${body}
]
`

  const outPath = resolve(__dirname, '../src/data/structures/gfp1EMA.ts')
  writeFileSync(outPath, output, 'utf-8')
  console.log(`Wrote ${outPath}`)
}

main()
